version: "3"
services:
  pushnotifications:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
    env_file:
      - .env
    container_name: push-notifications
    ports:
      - "5000:5000"